// Companies
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const GET_COMPANY_BY_ID = 'GET_A_COMPANY';
export const DELETE_COMPANY_BY_ID = 'DELETE_COMPANY_BY_ID';
export const SORT_COMPANIES = 'SORT_COMPANIES';
export const EDIT_COMPANY = 'EDIT_COMPANY';

// Deals
export const GET_ALL_DEALS = 'GET_ALL_DEALS';
export const GET_DEAL_POSITION = 'GET_DEAL_POSITION';
export const SET_DEAL_POSITION = 'SET_DEAL_POSITION';
export const GET_DEAL_BY_ID = 'GET_DEAL_BY_ID';
export const CREATE_DEAL = 'CREATE_DEAL';
export const DELETE_DEAL_BY_ID = 'DELETE_DEAL_BY_ID';

// Dashboard
export const GET_SUCCESS_RATE = 'GET_SUCCESS_RATE';
export const DEALS_IN_PROGRESS = 'DEALS_IN_PROGRESS';
export const GET_AVERAGE_REVENUE_PER_DEAL = 'GET_AVERAGE_REVENUE_PER_DEAL';
export const GET_TOTAL_REVENUE_TO_DATE = 'GET_TOTAL_REVENUE_TO_DATE';
export const GET_AVERAGE_TIME_TO_CLOSE_DEAL = 'GET_AVERAGE_TIME_TO_CLOSE_DEAL';
export const GET_TOP_THREE_CLIENTS = 'GET_TOP_THREE_CLIENTS';